/* 
 * OSP Enforcement (OSE)
 *
 *  The OSP enforcement component provides a set of functions that manage the interaction of OSP behaviour with the user's private data. The OSE component is largely in charge of ensuring that an OSP follows both privacy regulations and policies put in place by the user (i.e. in the OPERANDO UPPs). There are a set of events that trigger the usage of this API.  1) When a new G2C OSP registers with OPERANDO via the OPERANDO console. The management console informs the OSE, which then checks that an OSP conforms with existing privacy regulations; if it breaches the regulations, the OSE returns via the management console a report describing the breaches.  2) When a change of OSP privacy policy or of the OSP's privacy settings are detected by the watchdog component. The watchdog component sends a message to a privacy analyst who reviews any changes. The privacy analyst may then inform the OSE of the new OSP information (to be checked for compliance with regulations and users' UPPs.  3) When a privacy legislation is entered (or changed) via the Regulator API. The OSE checks registered OSPs for compliance with the new regulations; where there is a breach the OSP is notified either by e-mail or the console. 
 *
 * OpenAPI spec version: 0.0.8
 * Contact: support@operando.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace eu.operando.core.ose.cli.Model
{
    /// <summary>
    /// PrivacySetting
    /// </summary>
    [DataContract]
    public partial class PrivacySetting :  IEquatable<PrivacySetting>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PrivacySetting" /> class.
        /// </summary>
        /// <param name="Id">PrivacySetting Unique Identifier.</param>
        /// <param name="Description">Description of the setting.</param>
        /// <param name="Name">Short name of the setting(e.g. visibility).</param>
        /// <param name="SettingKey">Targeted setting key.</param>
        /// <param name="SettingValue">Targeted setting value.</param>
        public PrivacySetting(long? Id = null, string Description = null, string Name = null, string SettingKey = null, string SettingValue = null)
        {
            this.Id = Id;
            this.Description = Description;
            this.Name = Name;
            this.SettingKey = SettingKey;
            this.SettingValue = SettingValue;
        }
        
        /// <summary>
        /// PrivacySetting Unique Identifier
        /// </summary>
        /// <value>PrivacySetting Unique Identifier</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public long? Id { get; set; }
        /// <summary>
        /// Description of the setting
        /// </summary>
        /// <value>Description of the setting</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }
        /// <summary>
        /// Short name of the setting(e.g. visibility)
        /// </summary>
        /// <value>Short name of the setting(e.g. visibility)</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// Targeted setting key
        /// </summary>
        /// <value>Targeted setting key</value>
        [DataMember(Name="setting_key", EmitDefaultValue=false)]
        public string SettingKey { get; set; }
        /// <summary>
        /// Targeted setting value
        /// </summary>
        /// <value>Targeted setting value</value>
        [DataMember(Name="setting_value", EmitDefaultValue=false)]
        public string SettingValue { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PrivacySetting {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  SettingKey: ").Append(SettingKey).Append("\n");
            sb.Append("  SettingValue: ").Append(SettingValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as PrivacySetting);
        }

        /// <summary>
        /// Returns true if PrivacySetting instances are equal
        /// </summary>
        /// <param name="other">Instance of PrivacySetting to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PrivacySetting other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.Description == other.Description ||
                    this.Description != null &&
                    this.Description.Equals(other.Description)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.SettingKey == other.SettingKey ||
                    this.SettingKey != null &&
                    this.SettingKey.Equals(other.SettingKey)
                ) && 
                (
                    this.SettingValue == other.SettingValue ||
                    this.SettingValue != null &&
                    this.SettingValue.Equals(other.SettingValue)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this.Description != null)
                    hash = hash * 59 + this.Description.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.SettingKey != null)
                    hash = hash * 59 + this.SettingKey.GetHashCode();
                if (this.SettingValue != null)
                    hash = hash * 59 + this.SettingValue.GetHashCode();
                return hash;
            }
        }
    }

}
