/* 
 * Policy DB
 *
 * The Policy Database that stores three types of documents in dedicated collections.   1) User Privacy Policy. Each OPERANDO user has one UPP document describing their privacy policies for each of the OSP services they are subscribed to. The UPP contains the current B2C privacy settings for a subscribed to OSP. The UPP contains the users privacy preferences. The UPP contains the G2C access policies for the OSP with justification for access.   2) The legislation policies. The regulations entered into OPERANDO using the OPERANDO regulation API.   3) The OSP descriptions and data requests. For each OSP its privacy policy, its access control rules, and the data it requests (as a workflow). For B2C, the set of privacy settings is stored. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@operando.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using eu.operando.core.pdb.cli.Client;
using eu.operando.core.pdb.cli.Model;

namespace eu.operando.core.pdb.cli.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGETApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Perform a search query across the collection of OSP behaviour.
        /// </summary>
        /// <remarks>
        /// The query contains a json object (names, values) and the request returns the list of documents (regulations) where the filter matches i.e. the document contains fields with those values. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>List&lt;OSPPrivacyPolicy&gt;</returns>
        List<OSPPrivacyPolicy> OSPGet (string filter);

        /// <summary>
        /// Perform a search query across the collection of OSP behaviour.
        /// </summary>
        /// <remarks>
        /// The query contains a json object (names, values) and the request returns the list of documents (regulations) where the filter matches i.e. the document contains fields with those values. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>ApiResponse of List&lt;OSPPrivacyPolicy&gt;</returns>
        ApiResponse<List<OSPPrivacyPolicy>> OSPGetWithHttpInfo (string filter);
        /// <summary>
        /// Read a given OSP behaviour policy.
        /// </summary>
        /// <remarks>
        /// Get a specific OSP document via the id. This will return the full OSP document in json format. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>OSPPrivacyPolicy</returns>
        OSPPrivacyPolicy OSPOspIdGet (string ospId);

        /// <summary>
        /// Read a given OSP behaviour policy.
        /// </summary>
        /// <remarks>
        /// Get a specific OSP document via the id. This will return the full OSP document in json format. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>ApiResponse of OSPPrivacyPolicy</returns>
        ApiResponse<OSPPrivacyPolicy> OSPOspIdGetWithHttpInfo (string ospId);
        /// <summary>
        /// Get the list of access reason policy statements.
        /// </summary>
        /// <remarks>
        /// List of policy statements.  
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>List&lt;OSPReasonPolicy&gt;</returns>
        List<OSPReasonPolicy> OSPOspIdPrivacyPolicyAccessReasonsGet (string ospId);

        /// <summary>
        /// Get the list of access reason policy statements.
        /// </summary>
        /// <remarks>
        /// List of policy statements.  
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>ApiResponse of List&lt;OSPReasonPolicy&gt;</returns>
        ApiResponse<List<OSPReasonPolicy>> OSPOspIdPrivacyPolicyAccessReasonsGetWithHttpInfo (string ospId);
        /// <summary>
        /// Get the current set of privacy policy statements about the usage of data for stated reasons.
        /// </summary>
        /// <remarks>
        /// This is a machine readable version of a G2C privacy policy statement entered using the OSP Admin dashboard; and retrieved by both the OSP &amp; PSP analyst dashboard for display purposes and also by the OSE component for checking regulation compliance.  
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>OSPReasonPolicy</returns>
        OSPReasonPolicy OSPOspIdPrivacyPolicyGet (string ospId);

        /// <summary>
        /// Get the current set of privacy policy statements about the usage of data for stated reasons.
        /// </summary>
        /// <remarks>
        /// This is a machine readable version of a G2C privacy policy statement entered using the OSP Admin dashboard; and retrieved by both the OSP &amp; PSP analyst dashboard for display purposes and also by the OSE component for checking regulation compliance.  
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>ApiResponse of OSPReasonPolicy</returns>
        ApiResponse<OSPReasonPolicy> OSPOspIdPrivacyPolicyGetWithHttpInfo (string ospId);
        /// <summary>
        /// Perform a search query across the collection of regulation.
        /// </summary>
        /// <remarks>
        /// The query contains a json object (names, values) and the request returns  the list of documents (regulations) where the filter matches i.e. the  document contains fields with those values. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>List&lt;PrivacyRegulation&gt;</returns>
        List<PrivacyRegulation> RegulationsGet (string filter);

        /// <summary>
        /// Perform a search query across the collection of regulation.
        /// </summary>
        /// <remarks>
        /// The query contains a json object (names, values) and the request returns  the list of documents (regulations) where the filter matches i.e. the  document contains fields with those values. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>ApiResponse of List&lt;PrivacyRegulation&gt;</returns>
        ApiResponse<List<PrivacyRegulation>> RegulationsGetWithHttpInfo (string filter);
        /// <summary>
        /// Read a given legislation with its ID.
        /// </summary>
        /// <remarks>
        /// Get a specific legislation document via the id. This will return the  full legislation document in json format. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regId">The identifier number of a regulation</param>
        /// <returns>PrivacyRegulation</returns>
        PrivacyRegulation RegulationsRegIdGet (string regId);

        /// <summary>
        /// Read a given legislation with its ID.
        /// </summary>
        /// <remarks>
        /// Get a specific legislation document via the id. This will return the  full legislation document in json format. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regId">The identifier number of a regulation</param>
        /// <returns>ApiResponse of PrivacyRegulation</returns>
        ApiResponse<PrivacyRegulation> RegulationsRegIdGetWithHttpInfo (string regId);
        /// <summary>
        /// Perform a search query across the collection of UPPs.
        /// </summary>
        /// <remarks>
        /// The query contains a json object (names, values) and the request returns the list of documents (UPPs) where the filter matches i.e. each document contains fields with those values. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>List&lt;UserPrivacyPolicy&gt;</returns>
        List<UserPrivacyPolicy> UserPrivacyPolicyGet (string filter);

        /// <summary>
        /// Perform a search query across the collection of UPPs.
        /// </summary>
        /// <remarks>
        /// The query contains a json object (names, values) and the request returns the list of documents (UPPs) where the filter matches i.e. each document contains fields with those values. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>ApiResponse of List&lt;UserPrivacyPolicy&gt;</returns>
        ApiResponse<List<UserPrivacyPolicy>> UserPrivacyPolicyGetWithHttpInfo (string filter);
        /// <summary>
        /// Read the user privacy policy for the given user id.
        /// </summary>
        /// <remarks>
        /// Get a specific UPP document via the user&#39;s id. This will return the full user privacy policy document in json format. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The user identifier number</param>
        /// <returns>UserPrivacyPolicy</returns>
        UserPrivacyPolicy UserPrivacyPolicyUserIdGet (string userId);

        /// <summary>
        /// Read the user privacy policy for the given user id.
        /// </summary>
        /// <remarks>
        /// Get a specific UPP document via the user&#39;s id. This will return the full user privacy policy document in json format. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The user identifier number</param>
        /// <returns>ApiResponse of UserPrivacyPolicy</returns>
        ApiResponse<UserPrivacyPolicy> UserPrivacyPolicyUserIdGetWithHttpInfo (string userId);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Perform a search query across the collection of OSP behaviour.
        /// </summary>
        /// <remarks>
        /// The query contains a json object (names, values) and the request returns the list of documents (regulations) where the filter matches i.e. the document contains fields with those values. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>Task of List&lt;OSPPrivacyPolicy&gt;</returns>
        System.Threading.Tasks.Task<List<OSPPrivacyPolicy>> OSPGetAsync (string filter);

        /// <summary>
        /// Perform a search query across the collection of OSP behaviour.
        /// </summary>
        /// <remarks>
        /// The query contains a json object (names, values) and the request returns the list of documents (regulations) where the filter matches i.e. the document contains fields with those values. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>Task of ApiResponse (List&lt;OSPPrivacyPolicy&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<OSPPrivacyPolicy>>> OSPGetAsyncWithHttpInfo (string filter);
        /// <summary>
        /// Read a given OSP behaviour policy.
        /// </summary>
        /// <remarks>
        /// Get a specific OSP document via the id. This will return the full OSP document in json format. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>Task of OSPPrivacyPolicy</returns>
        System.Threading.Tasks.Task<OSPPrivacyPolicy> OSPOspIdGetAsync (string ospId);

        /// <summary>
        /// Read a given OSP behaviour policy.
        /// </summary>
        /// <remarks>
        /// Get a specific OSP document via the id. This will return the full OSP document in json format. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>Task of ApiResponse (OSPPrivacyPolicy)</returns>
        System.Threading.Tasks.Task<ApiResponse<OSPPrivacyPolicy>> OSPOspIdGetAsyncWithHttpInfo (string ospId);
        /// <summary>
        /// Get the list of access reason policy statements.
        /// </summary>
        /// <remarks>
        /// List of policy statements.  
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>Task of List&lt;OSPReasonPolicy&gt;</returns>
        System.Threading.Tasks.Task<List<OSPReasonPolicy>> OSPOspIdPrivacyPolicyAccessReasonsGetAsync (string ospId);

        /// <summary>
        /// Get the list of access reason policy statements.
        /// </summary>
        /// <remarks>
        /// List of policy statements.  
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>Task of ApiResponse (List&lt;OSPReasonPolicy&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<OSPReasonPolicy>>> OSPOspIdPrivacyPolicyAccessReasonsGetAsyncWithHttpInfo (string ospId);
        /// <summary>
        /// Get the current set of privacy policy statements about the usage of data for stated reasons.
        /// </summary>
        /// <remarks>
        /// This is a machine readable version of a G2C privacy policy statement entered using the OSP Admin dashboard; and retrieved by both the OSP &amp; PSP analyst dashboard for display purposes and also by the OSE component for checking regulation compliance.  
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>Task of OSPReasonPolicy</returns>
        System.Threading.Tasks.Task<OSPReasonPolicy> OSPOspIdPrivacyPolicyGetAsync (string ospId);

        /// <summary>
        /// Get the current set of privacy policy statements about the usage of data for stated reasons.
        /// </summary>
        /// <remarks>
        /// This is a machine readable version of a G2C privacy policy statement entered using the OSP Admin dashboard; and retrieved by both the OSP &amp; PSP analyst dashboard for display purposes and also by the OSE component for checking regulation compliance.  
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>Task of ApiResponse (OSPReasonPolicy)</returns>
        System.Threading.Tasks.Task<ApiResponse<OSPReasonPolicy>> OSPOspIdPrivacyPolicyGetAsyncWithHttpInfo (string ospId);
        /// <summary>
        /// Perform a search query across the collection of regulation.
        /// </summary>
        /// <remarks>
        /// The query contains a json object (names, values) and the request returns  the list of documents (regulations) where the filter matches i.e. the  document contains fields with those values. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>Task of List&lt;PrivacyRegulation&gt;</returns>
        System.Threading.Tasks.Task<List<PrivacyRegulation>> RegulationsGetAsync (string filter);

        /// <summary>
        /// Perform a search query across the collection of regulation.
        /// </summary>
        /// <remarks>
        /// The query contains a json object (names, values) and the request returns  the list of documents (regulations) where the filter matches i.e. the  document contains fields with those values. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>Task of ApiResponse (List&lt;PrivacyRegulation&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<PrivacyRegulation>>> RegulationsGetAsyncWithHttpInfo (string filter);
        /// <summary>
        /// Read a given legislation with its ID.
        /// </summary>
        /// <remarks>
        /// Get a specific legislation document via the id. This will return the  full legislation document in json format. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regId">The identifier number of a regulation</param>
        /// <returns>Task of PrivacyRegulation</returns>
        System.Threading.Tasks.Task<PrivacyRegulation> RegulationsRegIdGetAsync (string regId);

        /// <summary>
        /// Read a given legislation with its ID.
        /// </summary>
        /// <remarks>
        /// Get a specific legislation document via the id. This will return the  full legislation document in json format. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regId">The identifier number of a regulation</param>
        /// <returns>Task of ApiResponse (PrivacyRegulation)</returns>
        System.Threading.Tasks.Task<ApiResponse<PrivacyRegulation>> RegulationsRegIdGetAsyncWithHttpInfo (string regId);
        /// <summary>
        /// Perform a search query across the collection of UPPs.
        /// </summary>
        /// <remarks>
        /// The query contains a json object (names, values) and the request returns the list of documents (UPPs) where the filter matches i.e. each document contains fields with those values. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>Task of List&lt;UserPrivacyPolicy&gt;</returns>
        System.Threading.Tasks.Task<List<UserPrivacyPolicy>> UserPrivacyPolicyGetAsync (string filter);

        /// <summary>
        /// Perform a search query across the collection of UPPs.
        /// </summary>
        /// <remarks>
        /// The query contains a json object (names, values) and the request returns the list of documents (UPPs) where the filter matches i.e. each document contains fields with those values. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>Task of ApiResponse (List&lt;UserPrivacyPolicy&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<UserPrivacyPolicy>>> UserPrivacyPolicyGetAsyncWithHttpInfo (string filter);
        /// <summary>
        /// Read the user privacy policy for the given user id.
        /// </summary>
        /// <remarks>
        /// Get a specific UPP document via the user&#39;s id. This will return the full user privacy policy document in json format. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The user identifier number</param>
        /// <returns>Task of UserPrivacyPolicy</returns>
        System.Threading.Tasks.Task<UserPrivacyPolicy> UserPrivacyPolicyUserIdGetAsync (string userId);

        /// <summary>
        /// Read the user privacy policy for the given user id.
        /// </summary>
        /// <remarks>
        /// Get a specific UPP document via the user&#39;s id. This will return the full user privacy policy document in json format. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The user identifier number</param>
        /// <returns>Task of ApiResponse (UserPrivacyPolicy)</returns>
        System.Threading.Tasks.Task<ApiResponse<UserPrivacyPolicy>> UserPrivacyPolicyUserIdGetAsyncWithHttpInfo (string userId);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class GETApi : IGETApi
    {
        private eu.operando.core.pdb.cli.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="GETApi"/> class.
        /// </summary>
        /// <returns></returns>
        public GETApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = eu.operando.core.pdb.cli.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GETApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public GETApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = eu.operando.core.pdb.cli.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public eu.operando.core.pdb.cli.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Perform a search query across the collection of OSP behaviour. The query contains a json object (names, values) and the request returns the list of documents (regulations) where the filter matches i.e. the document contains fields with those values. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>List&lt;OSPPrivacyPolicy&gt;</returns>
        public List<OSPPrivacyPolicy> OSPGet (string filter)
        {
             ApiResponse<List<OSPPrivacyPolicy>> localVarResponse = OSPGetWithHttpInfo(filter);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Perform a search query across the collection of OSP behaviour. The query contains a json object (names, values) and the request returns the list of documents (regulations) where the filter matches i.e. the document contains fields with those values. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>ApiResponse of List&lt;OSPPrivacyPolicy&gt;</returns>
        public ApiResponse< List<OSPPrivacyPolicy> > OSPGetWithHttpInfo (string filter)
        {
            // verify the required parameter 'filter' is set
            if (filter == null)
                throw new ApiException(400, "Missing required parameter 'filter' when calling GETApi->OSPGet");

            var localVarPath = "/OSP/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (filter != null) localVarQueryParams.Add("filter", Configuration.ApiClient.ParameterToString(filter)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("OSPGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<OSPPrivacyPolicy>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<OSPPrivacyPolicy>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<OSPPrivacyPolicy>)));
            
        }

        /// <summary>
        /// Perform a search query across the collection of OSP behaviour. The query contains a json object (names, values) and the request returns the list of documents (regulations) where the filter matches i.e. the document contains fields with those values. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>Task of List&lt;OSPPrivacyPolicy&gt;</returns>
        public async System.Threading.Tasks.Task<List<OSPPrivacyPolicy>> OSPGetAsync (string filter)
        {
             ApiResponse<List<OSPPrivacyPolicy>> localVarResponse = await OSPGetAsyncWithHttpInfo(filter);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Perform a search query across the collection of OSP behaviour. The query contains a json object (names, values) and the request returns the list of documents (regulations) where the filter matches i.e. the document contains fields with those values. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>Task of ApiResponse (List&lt;OSPPrivacyPolicy&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<OSPPrivacyPolicy>>> OSPGetAsyncWithHttpInfo (string filter)
        {
            // verify the required parameter 'filter' is set
            if (filter == null)
                throw new ApiException(400, "Missing required parameter 'filter' when calling GETApi->OSPGet");

            var localVarPath = "/OSP/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (filter != null) localVarQueryParams.Add("filter", Configuration.ApiClient.ParameterToString(filter)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("OSPGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<OSPPrivacyPolicy>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<OSPPrivacyPolicy>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<OSPPrivacyPolicy>)));
            
        }

        /// <summary>
        /// Read a given OSP behaviour policy. Get a specific OSP document via the id. This will return the full OSP document in json format. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>OSPPrivacyPolicy</returns>
        public OSPPrivacyPolicy OSPOspIdGet (string ospId)
        {
             ApiResponse<OSPPrivacyPolicy> localVarResponse = OSPOspIdGetWithHttpInfo(ospId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Read a given OSP behaviour policy. Get a specific OSP document via the id. This will return the full OSP document in json format. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>ApiResponse of OSPPrivacyPolicy</returns>
        public ApiResponse< OSPPrivacyPolicy > OSPOspIdGetWithHttpInfo (string ospId)
        {
            // verify the required parameter 'ospId' is set
            if (ospId == null)
                throw new ApiException(400, "Missing required parameter 'ospId' when calling GETApi->OSPOspIdGet");

            var localVarPath = "/OSP/{osp-id}/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (ospId != null) localVarPathParams.Add("osp-id", Configuration.ApiClient.ParameterToString(ospId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("OSPOspIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OSPPrivacyPolicy>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OSPPrivacyPolicy) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OSPPrivacyPolicy)));
            
        }

        /// <summary>
        /// Read a given OSP behaviour policy. Get a specific OSP document via the id. This will return the full OSP document in json format. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>Task of OSPPrivacyPolicy</returns>
        public async System.Threading.Tasks.Task<OSPPrivacyPolicy> OSPOspIdGetAsync (string ospId)
        {
             ApiResponse<OSPPrivacyPolicy> localVarResponse = await OSPOspIdGetAsyncWithHttpInfo(ospId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Read a given OSP behaviour policy. Get a specific OSP document via the id. This will return the full OSP document in json format. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>Task of ApiResponse (OSPPrivacyPolicy)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<OSPPrivacyPolicy>> OSPOspIdGetAsyncWithHttpInfo (string ospId)
        {
            // verify the required parameter 'ospId' is set
            if (ospId == null)
                throw new ApiException(400, "Missing required parameter 'ospId' when calling GETApi->OSPOspIdGet");

            var localVarPath = "/OSP/{osp-id}/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (ospId != null) localVarPathParams.Add("osp-id", Configuration.ApiClient.ParameterToString(ospId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("OSPOspIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OSPPrivacyPolicy>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OSPPrivacyPolicy) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OSPPrivacyPolicy)));
            
        }

        /// <summary>
        /// Get the list of access reason policy statements. List of policy statements.  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>List&lt;OSPReasonPolicy&gt;</returns>
        public List<OSPReasonPolicy> OSPOspIdPrivacyPolicyAccessReasonsGet (string ospId)
        {
             ApiResponse<List<OSPReasonPolicy>> localVarResponse = OSPOspIdPrivacyPolicyAccessReasonsGetWithHttpInfo(ospId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get the list of access reason policy statements. List of policy statements.  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>ApiResponse of List&lt;OSPReasonPolicy&gt;</returns>
        public ApiResponse< List<OSPReasonPolicy> > OSPOspIdPrivacyPolicyAccessReasonsGetWithHttpInfo (string ospId)
        {
            // verify the required parameter 'ospId' is set
            if (ospId == null)
                throw new ApiException(400, "Missing required parameter 'ospId' when calling GETApi->OSPOspIdPrivacyPolicyAccessReasonsGet");

            var localVarPath = "/OSP/{osp-id}/privacy-policy/access-reasons";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (ospId != null) localVarPathParams.Add("osp-id", Configuration.ApiClient.ParameterToString(ospId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("OSPOspIdPrivacyPolicyAccessReasonsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<OSPReasonPolicy>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<OSPReasonPolicy>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<OSPReasonPolicy>)));
            
        }

        /// <summary>
        /// Get the list of access reason policy statements. List of policy statements.  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>Task of List&lt;OSPReasonPolicy&gt;</returns>
        public async System.Threading.Tasks.Task<List<OSPReasonPolicy>> OSPOspIdPrivacyPolicyAccessReasonsGetAsync (string ospId)
        {
             ApiResponse<List<OSPReasonPolicy>> localVarResponse = await OSPOspIdPrivacyPolicyAccessReasonsGetAsyncWithHttpInfo(ospId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get the list of access reason policy statements. List of policy statements.  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>Task of ApiResponse (List&lt;OSPReasonPolicy&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<OSPReasonPolicy>>> OSPOspIdPrivacyPolicyAccessReasonsGetAsyncWithHttpInfo (string ospId)
        {
            // verify the required parameter 'ospId' is set
            if (ospId == null)
                throw new ApiException(400, "Missing required parameter 'ospId' when calling GETApi->OSPOspIdPrivacyPolicyAccessReasonsGet");

            var localVarPath = "/OSP/{osp-id}/privacy-policy/access-reasons";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (ospId != null) localVarPathParams.Add("osp-id", Configuration.ApiClient.ParameterToString(ospId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("OSPOspIdPrivacyPolicyAccessReasonsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<OSPReasonPolicy>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<OSPReasonPolicy>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<OSPReasonPolicy>)));
            
        }

        /// <summary>
        /// Get the current set of privacy policy statements about the usage of data for stated reasons. This is a machine readable version of a G2C privacy policy statement entered using the OSP Admin dashboard; and retrieved by both the OSP &amp; PSP analyst dashboard for display purposes and also by the OSE component for checking regulation compliance.  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>OSPReasonPolicy</returns>
        public OSPReasonPolicy OSPOspIdPrivacyPolicyGet (string ospId)
        {
             ApiResponse<OSPReasonPolicy> localVarResponse = OSPOspIdPrivacyPolicyGetWithHttpInfo(ospId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get the current set of privacy policy statements about the usage of data for stated reasons. This is a machine readable version of a G2C privacy policy statement entered using the OSP Admin dashboard; and retrieved by both the OSP &amp; PSP analyst dashboard for display purposes and also by the OSE component for checking regulation compliance.  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>ApiResponse of OSPReasonPolicy</returns>
        public ApiResponse< OSPReasonPolicy > OSPOspIdPrivacyPolicyGetWithHttpInfo (string ospId)
        {
            // verify the required parameter 'ospId' is set
            if (ospId == null)
                throw new ApiException(400, "Missing required parameter 'ospId' when calling GETApi->OSPOspIdPrivacyPolicyGet");

            var localVarPath = "/OSP/{osp-id}/privacy-policy/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (ospId != null) localVarPathParams.Add("osp-id", Configuration.ApiClient.ParameterToString(ospId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("OSPOspIdPrivacyPolicyGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OSPReasonPolicy>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OSPReasonPolicy) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OSPReasonPolicy)));
            
        }

        /// <summary>
        /// Get the current set of privacy policy statements about the usage of data for stated reasons. This is a machine readable version of a G2C privacy policy statement entered using the OSP Admin dashboard; and retrieved by both the OSP &amp; PSP analyst dashboard for display purposes and also by the OSE component for checking regulation compliance.  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>Task of OSPReasonPolicy</returns>
        public async System.Threading.Tasks.Task<OSPReasonPolicy> OSPOspIdPrivacyPolicyGetAsync (string ospId)
        {
             ApiResponse<OSPReasonPolicy> localVarResponse = await OSPOspIdPrivacyPolicyGetAsyncWithHttpInfo(ospId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get the current set of privacy policy statements about the usage of data for stated reasons. This is a machine readable version of a G2C privacy policy statement entered using the OSP Admin dashboard; and retrieved by both the OSP &amp; PSP analyst dashboard for display purposes and also by the OSE component for checking regulation compliance.  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ospId">The identifier number of an OSP</param>
        /// <returns>Task of ApiResponse (OSPReasonPolicy)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<OSPReasonPolicy>> OSPOspIdPrivacyPolicyGetAsyncWithHttpInfo (string ospId)
        {
            // verify the required parameter 'ospId' is set
            if (ospId == null)
                throw new ApiException(400, "Missing required parameter 'ospId' when calling GETApi->OSPOspIdPrivacyPolicyGet");

            var localVarPath = "/OSP/{osp-id}/privacy-policy/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (ospId != null) localVarPathParams.Add("osp-id", Configuration.ApiClient.ParameterToString(ospId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("OSPOspIdPrivacyPolicyGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OSPReasonPolicy>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OSPReasonPolicy) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OSPReasonPolicy)));
            
        }

        /// <summary>
        /// Perform a search query across the collection of regulation. The query contains a json object (names, values) and the request returns  the list of documents (regulations) where the filter matches i.e. the  document contains fields with those values. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>List&lt;PrivacyRegulation&gt;</returns>
        public List<PrivacyRegulation> RegulationsGet (string filter)
        {
             ApiResponse<List<PrivacyRegulation>> localVarResponse = RegulationsGetWithHttpInfo(filter);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Perform a search query across the collection of regulation. The query contains a json object (names, values) and the request returns  the list of documents (regulations) where the filter matches i.e. the  document contains fields with those values. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>ApiResponse of List&lt;PrivacyRegulation&gt;</returns>
        public ApiResponse< List<PrivacyRegulation> > RegulationsGetWithHttpInfo (string filter)
        {
            // verify the required parameter 'filter' is set
            if (filter == null)
                throw new ApiException(400, "Missing required parameter 'filter' when calling GETApi->RegulationsGet");

            var localVarPath = "/regulations/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (filter != null) localVarQueryParams.Add("filter", Configuration.ApiClient.ParameterToString(filter)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RegulationsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<PrivacyRegulation>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<PrivacyRegulation>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<PrivacyRegulation>)));
            
        }

        /// <summary>
        /// Perform a search query across the collection of regulation. The query contains a json object (names, values) and the request returns  the list of documents (regulations) where the filter matches i.e. the  document contains fields with those values. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>Task of List&lt;PrivacyRegulation&gt;</returns>
        public async System.Threading.Tasks.Task<List<PrivacyRegulation>> RegulationsGetAsync (string filter)
        {
             ApiResponse<List<PrivacyRegulation>> localVarResponse = await RegulationsGetAsyncWithHttpInfo(filter);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Perform a search query across the collection of regulation. The query contains a json object (names, values) and the request returns  the list of documents (regulations) where the filter matches i.e. the  document contains fields with those values. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>Task of ApiResponse (List&lt;PrivacyRegulation&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<PrivacyRegulation>>> RegulationsGetAsyncWithHttpInfo (string filter)
        {
            // verify the required parameter 'filter' is set
            if (filter == null)
                throw new ApiException(400, "Missing required parameter 'filter' when calling GETApi->RegulationsGet");

            var localVarPath = "/regulations/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (filter != null) localVarQueryParams.Add("filter", Configuration.ApiClient.ParameterToString(filter)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RegulationsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<PrivacyRegulation>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<PrivacyRegulation>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<PrivacyRegulation>)));
            
        }

        /// <summary>
        /// Read a given legislation with its ID. Get a specific legislation document via the id. This will return the  full legislation document in json format. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regId">The identifier number of a regulation</param>
        /// <returns>PrivacyRegulation</returns>
        public PrivacyRegulation RegulationsRegIdGet (string regId)
        {
             ApiResponse<PrivacyRegulation> localVarResponse = RegulationsRegIdGetWithHttpInfo(regId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Read a given legislation with its ID. Get a specific legislation document via the id. This will return the  full legislation document in json format. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regId">The identifier number of a regulation</param>
        /// <returns>ApiResponse of PrivacyRegulation</returns>
        public ApiResponse< PrivacyRegulation > RegulationsRegIdGetWithHttpInfo (string regId)
        {
            // verify the required parameter 'regId' is set
            if (regId == null)
                throw new ApiException(400, "Missing required parameter 'regId' when calling GETApi->RegulationsRegIdGet");

            var localVarPath = "/regulations/{reg-id}/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (regId != null) localVarPathParams.Add("reg-id", Configuration.ApiClient.ParameterToString(regId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RegulationsRegIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PrivacyRegulation>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PrivacyRegulation) Configuration.ApiClient.Deserialize(localVarResponse, typeof(PrivacyRegulation)));
            
        }

        /// <summary>
        /// Read a given legislation with its ID. Get a specific legislation document via the id. This will return the  full legislation document in json format. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regId">The identifier number of a regulation</param>
        /// <returns>Task of PrivacyRegulation</returns>
        public async System.Threading.Tasks.Task<PrivacyRegulation> RegulationsRegIdGetAsync (string regId)
        {
             ApiResponse<PrivacyRegulation> localVarResponse = await RegulationsRegIdGetAsyncWithHttpInfo(regId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Read a given legislation with its ID. Get a specific legislation document via the id. This will return the  full legislation document in json format. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="regId">The identifier number of a regulation</param>
        /// <returns>Task of ApiResponse (PrivacyRegulation)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PrivacyRegulation>> RegulationsRegIdGetAsyncWithHttpInfo (string regId)
        {
            // verify the required parameter 'regId' is set
            if (regId == null)
                throw new ApiException(400, "Missing required parameter 'regId' when calling GETApi->RegulationsRegIdGet");

            var localVarPath = "/regulations/{reg-id}/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (regId != null) localVarPathParams.Add("reg-id", Configuration.ApiClient.ParameterToString(regId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RegulationsRegIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PrivacyRegulation>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PrivacyRegulation) Configuration.ApiClient.Deserialize(localVarResponse, typeof(PrivacyRegulation)));
            
        }

        /// <summary>
        /// Perform a search query across the collection of UPPs. The query contains a json object (names, values) and the request returns the list of documents (UPPs) where the filter matches i.e. each document contains fields with those values. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>List&lt;UserPrivacyPolicy&gt;</returns>
        public List<UserPrivacyPolicy> UserPrivacyPolicyGet (string filter)
        {
             ApiResponse<List<UserPrivacyPolicy>> localVarResponse = UserPrivacyPolicyGetWithHttpInfo(filter);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Perform a search query across the collection of UPPs. The query contains a json object (names, values) and the request returns the list of documents (UPPs) where the filter matches i.e. each document contains fields with those values. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>ApiResponse of List&lt;UserPrivacyPolicy&gt;</returns>
        public ApiResponse< List<UserPrivacyPolicy> > UserPrivacyPolicyGetWithHttpInfo (string filter)
        {
            // verify the required parameter 'filter' is set
            if (filter == null)
                throw new ApiException(400, "Missing required parameter 'filter' when calling GETApi->UserPrivacyPolicyGet");

            var localVarPath = "/user_privacy_policy/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (filter != null) localVarQueryParams.Add("filter", Configuration.ApiClient.ParameterToString(filter)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UserPrivacyPolicyGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<UserPrivacyPolicy>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<UserPrivacyPolicy>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<UserPrivacyPolicy>)));
            
        }

        /// <summary>
        /// Perform a search query across the collection of UPPs. The query contains a json object (names, values) and the request returns the list of documents (UPPs) where the filter matches i.e. each document contains fields with those values. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>Task of List&lt;UserPrivacyPolicy&gt;</returns>
        public async System.Threading.Tasks.Task<List<UserPrivacyPolicy>> UserPrivacyPolicyGetAsync (string filter)
        {
             ApiResponse<List<UserPrivacyPolicy>> localVarResponse = await UserPrivacyPolicyGetAsyncWithHttpInfo(filter);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Perform a search query across the collection of UPPs. The query contains a json object (names, values) and the request returns the list of documents (UPPs) where the filter matches i.e. each document contains fields with those values. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">The query filter to be matched - ?filter&#x3D;{json description}</param>
        /// <returns>Task of ApiResponse (List&lt;UserPrivacyPolicy&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<UserPrivacyPolicy>>> UserPrivacyPolicyGetAsyncWithHttpInfo (string filter)
        {
            // verify the required parameter 'filter' is set
            if (filter == null)
                throw new ApiException(400, "Missing required parameter 'filter' when calling GETApi->UserPrivacyPolicyGet");

            var localVarPath = "/user_privacy_policy/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (filter != null) localVarQueryParams.Add("filter", Configuration.ApiClient.ParameterToString(filter)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UserPrivacyPolicyGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<UserPrivacyPolicy>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<UserPrivacyPolicy>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<UserPrivacyPolicy>)));
            
        }

        /// <summary>
        /// Read the user privacy policy for the given user id. Get a specific UPP document via the user&#39;s id. This will return the full user privacy policy document in json format. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The user identifier number</param>
        /// <returns>UserPrivacyPolicy</returns>
        public UserPrivacyPolicy UserPrivacyPolicyUserIdGet (string userId)
        {
             ApiResponse<UserPrivacyPolicy> localVarResponse = UserPrivacyPolicyUserIdGetWithHttpInfo(userId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Read the user privacy policy for the given user id. Get a specific UPP document via the user&#39;s id. This will return the full user privacy policy document in json format. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The user identifier number</param>
        /// <returns>ApiResponse of UserPrivacyPolicy</returns>
        public ApiResponse< UserPrivacyPolicy > UserPrivacyPolicyUserIdGetWithHttpInfo (string userId)
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling GETApi->UserPrivacyPolicyUserIdGet");

            var localVarPath = "/user_privacy_policy/{user-id}/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (userId != null) localVarPathParams.Add("user-id", Configuration.ApiClient.ParameterToString(userId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UserPrivacyPolicyUserIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<UserPrivacyPolicy>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (UserPrivacyPolicy) Configuration.ApiClient.Deserialize(localVarResponse, typeof(UserPrivacyPolicy)));
            
        }

        /// <summary>
        /// Read the user privacy policy for the given user id. Get a specific UPP document via the user&#39;s id. This will return the full user privacy policy document in json format. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The user identifier number</param>
        /// <returns>Task of UserPrivacyPolicy</returns>
        public async System.Threading.Tasks.Task<UserPrivacyPolicy> UserPrivacyPolicyUserIdGetAsync (string userId)
        {
             ApiResponse<UserPrivacyPolicy> localVarResponse = await UserPrivacyPolicyUserIdGetAsyncWithHttpInfo(userId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Read the user privacy policy for the given user id. Get a specific UPP document via the user&#39;s id. This will return the full user privacy policy document in json format. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The user identifier number</param>
        /// <returns>Task of ApiResponse (UserPrivacyPolicy)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<UserPrivacyPolicy>> UserPrivacyPolicyUserIdGetAsyncWithHttpInfo (string userId)
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling GETApi->UserPrivacyPolicyUserIdGet");

            var localVarPath = "/user_privacy_policy/{user-id}/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (userId != null) localVarPathParams.Add("user-id", Configuration.ApiClient.ParameterToString(userId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UserPrivacyPolicyUserIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<UserPrivacyPolicy>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (UserPrivacyPolicy) Configuration.ApiClient.Deserialize(localVarResponse, typeof(UserPrivacyPolicy)));
            
        }

    }
}
