//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WebResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your privacy preferences are shown here. You can see, and change, which organisations have access to your data and how it is used. These settings are enforced automatically for you by OPERANDO, an  independent platform, to ensure that your data is only used in ways  which you have agreed to..
        /// </summary>
        internal static string AccessPreferencesDescription {
            get {
                return ResourceManager.GetString("AccessPreferencesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy settings for the app.
        /// </summary>
        internal static string AccessPreferencesOSPPrivacySettings {
            get {
                return ResourceManager.GetString("AccessPreferencesOSPPrivacySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to default values.
        /// </summary>
        internal static string AccessPreferencesReverseUPPToDefault {
            get {
                return ResourceManager.GetString("AccessPreferencesReverseUPPToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should be able to access the following data:.
        /// </summary>
        internal static string AccessPreferencesRoleShouldBeAbleToAccess {
            get {
                return ResourceManager.GetString("AccessPreferencesRoleShouldBeAbleToAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIVACY WIZARD.
        /// </summary>
        internal static string AccessPreferencesSubtitle {
            get {
                return ResourceManager.GetString("AccessPreferencesSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access preferences.
        /// </summary>
        internal static string AccessPreferencesTitle {
            get {
                return ResourceManager.GetString("AccessPreferencesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update UPP (User Privacy Policy).
        /// </summary>
        internal static string AccessPreferencesUpdateUPP {
            get {
                return ResourceManager.GetString("AccessPreferencesUpdateUPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your privacy settings are:.
        /// </summary>
        internal static string AccessPreferencesYourPrivacySettings {
            get {
                return ResourceManager.GetString("AccessPreferencesYourPrivacySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to According to your privacy settings, access was granted for.
        /// </summary>
        internal static string AccessWasGrantedFor {
            get {
                return ResourceManager.GetString("AccessWasGrantedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to According to your privacy settings, access was not granted for.
        /// </summary>
        internal static string AccessWasNotGrantedFor {
            get {
                return ResourceManager.GetString("AccessWasNotGrantedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and was not granted for.
        /// </summary>
        internal static string AndWasNotGrantedFor {
            get {
                return ResourceManager.GetString("AndWasNotGrantedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to know more about how OPERANDO works, visit the project website: .
        /// </summary>
        internal static string DashboardLinkToProject {
            get {
                return ResourceManager.GetString("DashboardLinkToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You give your personal information to many organisations in order to use their services, and agree to many terms and policies to do so. It can be difficult to keep track of who has access to your data, or update how you would like it to be used. This OPERANDO dashboard shows you a summary of: notifications about any changes to services and how your data is used, requests for the use of your data and links to other areas so you can make changes in response to this information..
        /// </summary>
        internal static string DashboardMotivation {
            get {
                return ResourceManager.GetString("DashboardMotivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The homepage acts as a dashboard; a central place where you are able to manage the privacy of your personal information..
        /// </summary>
        internal static string DashboardOverview {
            get {
                return ResourceManager.GetString("DashboardOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOST RECENT DATA REQUESTS.
        /// </summary>
        internal static string DashboardRecentDataRequests {
            get {
                return ResourceManager.GetString("DashboardRecentDataRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOST RECENT NOTIFICATIONS.
        /// </summary>
        internal static string DashboardRecentNotifications {
            get {
                return ResourceManager.GetString("DashboardRecentNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your privacy settings were updated because of changes you made through the dashboard..
        /// </summary>
        internal static string DashboardSettingsUpdated {
            get {
                return ResourceManager.GetString("DashboardSettingsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string DashboardSubtitle {
            get {
                return ResourceManager.GetString("DashboardSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        internal static string DashboardViewAllButton {
            get {
                return ResourceManager.GetString("DashboardViewAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This log shows how your data is being used. Each request, whether accepted or rejected, is shown. These results reflect the settings in your privacy preferences, and allow you to see your choices being enforced.
        /// </summary>
        internal static string DataAccessLogsSubtitle {
            get {
                return ResourceManager.GetString("DataAccessLogsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data access logs.
        /// </summary>
        internal static string DataAccessLogsTitle {
            get {
                return ResourceManager.GetString("DataAccessLogsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data subject.
        /// </summary>
        internal static string DataSubjectName {
            get {
                return ResourceManager.GetString("DataSubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        internal static string LogAccessDenied {
            get {
                return ResourceManager.GetString("LogAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access granted.
        /// </summary>
        internal static string LogAccessGranted {
            get {
                return ResourceManager.GetString("LogAccessGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string LogActions {
            get {
                return ResourceManager.GetString("LogActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string LogDate {
            get {
                return ResourceManager.GetString("LogDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit OSP settings.
        /// </summary>
        internal static string LogEditOSPSettingsButton {
            get {
                return ResourceManager.GetString("LogEditOSPSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Type.
        /// </summary>
        internal static string LogFilterByType {
            get {
                return ResourceManager.GetString("LogFilterByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE AN ACCOUNT.
        /// </summary>
        internal static string LoginNewAccount {
            get {
                return ResourceManager.GetString("LoginNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string LoginPasswordForgot {
            get {
                return ResourceManager.GetString("LoginPasswordForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember.
        /// </summary>
        internal static string LoginRemember {
            get {
                return ResourceManager.GetString("LoginRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string LoginSubtitle {
            get {
                return ResourceManager.GetString("LoginSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login - Operando G2C.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string LoginUsername {
            get {
                return ResourceManager.GetString("LoginUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string LogMessage {
            get {
                return ResourceManager.GetString("LogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requested access to your.
        /// </summary>
        internal static string LogRequestedAccess {
            get {
                return ResourceManager.GetString("LogRequestedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was allowed, because it did comply with your privacy settings.
        /// </summary>
        internal static string LogRequestedAccessAllowed {
            get {
                return ResourceManager.GetString("LogRequestedAccessAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was denied, because it did not comply with your privacy settings.
        /// </summary>
        internal static string LogRequestedAccessDenied {
            get {
                return ResourceManager.GetString("LogRequestedAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester.
        /// </summary>
        internal static string LogRequester {
            get {
                return ResourceManager.GetString("LogRequester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string LogSearch {
            get {
                return ResourceManager.GetString("LogSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string LogShow {
            get {
                return ResourceManager.GetString("LogShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        internal static string LogShowingRecap {
            get {
                return ResourceManager.GetString("LogShowingRecap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string LogTitle {
            get {
                return ResourceManager.GetString("LogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string LogType {
            get {
                return ResourceManager.GetString("LogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Preferences.
        /// </summary>
        internal static string MenuAccessPreferences {
            get {
                return ResourceManager.GetString("MenuAccessPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string MenuDashboard {
            get {
                return ResourceManager.GetString("MenuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Access Log.
        /// </summary>
        internal static string MenuDataAccessLog {
            get {
                return ResourceManager.GetString("MenuDataAccessLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string MenuNotifications {
            get {
                return ResourceManager.GetString("MenuNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Action.
        /// </summary>
        internal static string NotificationActionHeader {
            get {
                return ResourceManager.GetString("NotificationActionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to page.
        /// </summary>
        internal static string NotificationActionStr {
            get {
                return ResourceManager.GetString("NotificationActionStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string NotificationsDate {
            get {
                return ResourceManager.GetString("NotificationsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events relevant to you (e.g. pending data access requests, recommended/automatic changes to settings) are displayed in this section. Requests are shown with the most recent first, but you can filter (Pending, Approved, Requested) or search freely..
        /// </summary>
        internal static string NotificationsDescription {
            get {
                return ResourceManager.GetString("NotificationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found.
        /// </summary>
        internal static string NotificationsEmpty {
            get {
                return ResourceManager.GetString("NotificationsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string NotificationsMessage {
            get {
                return ResourceManager.GetString("NotificationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available in table.
        /// </summary>
        internal static string NotificationsNoData {
            get {
                return ResourceManager.GetString("NotificationsNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string NotificationsSearch {
            get {
                return ResourceManager.GetString("NotificationsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string NotificationsShow {
            get {
                return ResourceManager.GetString("NotificationsShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string NotificationsTitle {
            get {
                return ResourceManager.GetString("NotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string NotificationsType {
            get {
                return ResourceManager.GetString("NotificationsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your account details below: .
        /// </summary>
        internal static string RegistrationAccountDetails {
            get {
                return ResourceManager.GetString("RegistrationAccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string RegistrationAddress {
            get {
                return ResourceManager.GetString("RegistrationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string RegistrationBackButton {
            get {
                return ResourceManager.GetString("RegistrationBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City/Town.
        /// </summary>
        internal static string RegistrationCity {
            get {
                return ResourceManager.GetString("RegistrationCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string RegistrationCountry {
            get {
                return ResourceManager.GetString("RegistrationCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string RegistrationEmail {
            get {
                return ResourceManager.GetString("RegistrationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string RegistrationFullName {
            get {
                return ResourceManager.GetString("RegistrationFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string RegistrationPassword {
            get {
                return ResourceManager.GetString("RegistrationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-type Your Password.
        /// </summary>
        internal static string RegistrationPasswordConfirm {
            get {
                return ResourceManager.GetString("RegistrationPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT.
        /// </summary>
        internal static string RegistrationSubmitButton {
            get {
                return ResourceManager.GetString("RegistrationSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your personal details below:.
        /// </summary>
        internal static string RegistrationSubtitle {
            get {
                return ResourceManager.GetString("RegistrationSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the Terms of Service &amp; Privacy Policy.
        /// </summary>
        internal static string RegistrationTerms {
            get {
                return ResourceManager.GetString("RegistrationTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string RegistrationTitle {
            get {
                return ResourceManager.GetString("RegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string RegistrationUsername {
            get {
                return ResourceManager.GetString("RegistrationUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type.
        /// </summary>
        internal static string RegistrationUserType {
            get {
                return ResourceManager.GetString("RegistrationUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requested access to the following data.
        /// </summary>
        internal static string RequestedAccessTo {
            get {
                return ResourceManager.GetString("RequestedAccessTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Subject.
        /// </summary>
        internal static string SectionDataSubject {
            get {
                return ResourceManager.GetString("SectionDataSubject", resourceCulture);
            }
        }
    }
}
