/* 
 * REST API for CPCU Operando
 *
 * A REST API to access and edit Questionnaires and Services within the CPCU platform
 *
 * OpenAPI spec version: 2.0
 * Contact: support@operando.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ServiceConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ServiceConfigurationTests
    {
        // TODO uncomment below to declare an instance variable for ServiceConfiguration
        //private ServiceConfiguration instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ServiceConfiguration
            //instance = new ServiceConfiguration();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ServiceConfiguration
        /// </summary>
        [Test]
        public void ServiceConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ServiceConfiguration
            //Assert.IsInstanceOfType<ServiceConfiguration> (instance, "variable 'instance' is a ServiceConfiguration");
        }

        /// <summary>
        /// Test the property 'AquisitionMethod'
        /// </summary>
        [Test]
        public void AquisitionMethodTest()
        {
            // TODO unit test for the property 'AquisitionMethod'
        }
        /// <summary>
        /// Test the property 'DataLocation'
        /// </summary>
        [Test]
        public void DataLocationTest()
        {
            // TODO unit test for the property 'DataLocation'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'Preference'
        /// </summary>
        [Test]
        public void PreferenceTest()
        {
            // TODO unit test for the property 'Preference'
        }
        /// <summary>
        /// Test the property 'RoleLocation'
        /// </summary>
        [Test]
        public void RoleLocationTest()
        {
            // TODO unit test for the property 'RoleLocation'
        }

    }

}
