/* 
 * REST API for CPCU Operando
 *
 * A REST API to access and edit Questionnaires and Services within the CPCU platform
 *
 * OpenAPI spec version: 2.0
 * Contact: support@operando.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GETCPCUApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class GETCPCUApiTests
    {
        private GETCPCUApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new GETCPCUApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GETCPCUApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' GETCPCUApi
            //Assert.IsInstanceOfType(typeof(GETCPCUApi), instance, "instance is a GETCPCUApi");
        }

        
        /// <summary>
        /// Test GetCPCUGET
        /// </summary>
        [Test]
        public void GetCPCUGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userID = null;
            //int? serviceID = null;
            //int? questionnaireID = null;
            //var response = instance.GetCPCUGET(userID, serviceID, questionnaireID);
            //Assert.IsInstanceOf<QNRootObject> (response, "response is QNRootObject");
        }
        
    }

}
