/* 
 * Policy DB
 *
 * The Policy Database that stores three types of documents in dedicated collections.   1) User Privacy Policy. Each OPERANDO user has one UPP document describing their privacy policies for each of the OSP services they are subscribed to. The UPP contains the current B2C privacy settings for a subscribed to OSP. The UPP contains the users privacy preferences. The UPP contains the G2C access policies for the OSP with justification for access.   2) The legislation policies. The regulations entered into OPERANDO using the OPERANDO regulation API.   3) The OSP descriptions and data requests. For each OSP its privacy policy, its access control rules, and the data it requests (as a workflow). For B2C, the set of privacy settings is stored. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@operando.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DELETEApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DELETEApiTests
    {
        private DELETEApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DELETEApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DELETEApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DELETEApi
            //Assert.IsInstanceOfType(typeof(DELETEApi), instance, "instance is a DELETEApi");
        }

        
        /// <summary>
        /// Test OSPOspIdDelete
        /// </summary>
        [Test]
        public void OSPOspIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string ospId = null;
            //instance.OSPOspIdDelete(ospId);
            
        }
        
        /// <summary>
        /// Test OSPOspIdPrivacyPolicyAccessReasonsReasonIdDelete
        /// </summary>
        [Test]
        public void OSPOspIdPrivacyPolicyAccessReasonsReasonIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string ospId = null;
            //string reasonId = null;
            //instance.OSPOspIdPrivacyPolicyAccessReasonsReasonIdDelete(ospId, reasonId);
            
        }
        
        /// <summary>
        /// Test RegulationsRegIdDelete
        /// </summary>
        [Test]
        public void RegulationsRegIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string regId = null;
            //instance.RegulationsRegIdDelete(regId);
            
        }
        
        /// <summary>
        /// Test UserPrivacyPolicyUserIdDelete
        /// </summary>
        [Test]
        public void UserPrivacyPolicyUserIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //instance.UserPrivacyPolicyUserIdDelete(userId);
            
        }
        
    }

}
